[workspace]
members = [
  "cmd",
  "calculator"]
resolver = "2"

[workspace.dependencies]
wit-bindgen-rt = { version = "0.39.0", features = ["bitflags"] }

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

