[package]
name = "adder"
version = "0.1.0"
edition = "2021"

[package.metadata.component]
package = "docs:adder"

[package.metadata.component.target]
path = "../wit/adder"
world = "adder"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen-rt.workspace = true
